name: ci

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Get Project Info
        id: info
        run: |
          echo "name=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_OUTPUT
          echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Build
        run: mvn clean install -Pprod

      - name: Generate Release
        id: release
        run: gh release create v${{steps.info.outputs.version}} --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        id: login
        uses: docker/login-action@v3
        with:
          username: ${{github.repository_owner}}
          password: ${{ secrets.DH_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{github.repository_owner}}/${{steps.info.outputs.name}}:latest, ${{github.repository_owner}}/${{steps.info.outputs.name}}:${{steps.info.outputs.version}}

      - name: Update Repo Description
        id: repo
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{github.repository_owner}}
          password: ${{ secrets.DH_TOKEN }}
          repository: ${{github.repository_owner}}/${{steps.info.outputs.name}}

      - name: Success Discord Notification
        if: success()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Sucesso no build!
          username: Octocat
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}

      - name: Failure Discord Notification
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: ${{ join(steps.build.outputs.*, '\n') }}
          username: Octocat
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
